### PR TITLE
Fix missing datetime "unit" and Ghrsst2ioda output "K" to "C"

### LINKED ISSUE #830: The Ghrsst2Ioda converter should output C instead of K

### LINKED ISSUE #831: Missing datetime "units"
A residual bug from an mpi implementation ... Ask @AndrewEichmann-NOAA for the fix

### PR DESCRIPTION
**Pull request by apchoiCMD**
This PR fixes two bugs:

1. Missing datetime "units"
2. Ghrsst2ioda converter outputs sea surface temperature with unit "C"

All outputs are placed at each issue at https://github.com/NOAA-EMC/GDASApp/issues/831 and https://github.com/NOAA-EMC/GDASApp/issues/830

Close https://github.com/NOAA-EMC/GDASApp/issues/831 , Close https://github.com/NOAA-EMC/GDASApp/issues/830

### CODE REVIEW

File: utils/obsproc/Ghrsst2Ioda.h [hunk 1]
```diff
@@ -37,8 +37,8 @@ namespace gdasapp {
       float sstMax;
       fullConfig_.get("bounds.max", sstMax);
       if ( sstUnits == "C" ) {
```
Comment (guillaumevernieres) [inline utils/obsproc/Ghrsst2Ioda.h]: Keep the condition below as it was originally but replace "C" with "K". No point doing `+=0` ...
Or just remove the option and just assume we only deal with C.

**Review by ShastriPaturi — DISMISSED** [review]
Looks good to me.

**Review by AndrewEichmann-NOAA — DISMISSED** [review]
Looks good

**Review by guillaumevernieres — COMMENTED** [review]
We should probably entirely remove the option of outputting K and just assume everything is in C.

File: utils/obsproc/Ghrsst2Ioda.h (hunk 1 above)
Comment (apchoiCMD) [reply utils/obsproc/Ghrsst2Ioda.h]: > Keep the condition below as it was originally but replace "C" with "K". No point doing `+=0` ... Or just remove the option and just assume we only deal with C.

@guillaumevernieres I will push again with your comment.

**Review by guillaumevernieres — COMMENTED** [review]
[that line](https://github.com/NOAA-EMC/GDASApp/blob/a34773ad8f80d2074e0528caae97d70d2f23afd7/utils/test/testinput/gdas_ghrsst2ioda.yaml#L8)  is not needed anymore.

**Comment by apchoiCMD** [comment]
> [that line](https://github.com/NOAA-EMC/GDASApp/blob/a34773ad8f80d2074e0528caae97d70d2f23afd7/utils/test/testinput/gdas_ghrsst2ioda.yaml#L8) is not needed anymore.

ha! thanks for heading me up! Pushing again...

**Review by guillaumevernieres — APPROVED** [review]
Thanks @apchoiCMD
